name: CI Process
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  behave-testing:
    # setup of simple OS of choice, i.e. Linux
    # create VM with ubuntu OS
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from repository
      - name: Checkout
        uses: actions/checkout@v4.2.2

      # Step 2: List files in the repository
      - name: List repo
        run: |
          ls

      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.9'

      # Step 4: Install a Python package using pip-install-package-action
      - name: Install Python package
        uses: durandtibo/pip-install-package-action@v0.3.1
        with:
          # Specify the package name and version you want to install
          package-name: behave    # Replace with the actual package name
          package-version: '1.2.6'  # Replace with the desired version, or leave blank for the latest
          python-version: '3.9'
    
      - name: Run Behave tests
        run: |
          behave  # Make sure features/ directory exists in your repo

# Week13 - Step 6b: Send Telegram Message on failure 
      - name: Send Telegram Message on Test Failure(s)
        if: failure()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
          -d chat_id="${TELEGRAM_CHAT_ID}" \
          -d text="Review failed run, fix the issue(s), and re-run until successful."  
